import type { ThemeData } from './types';

/**
 * Мир 3 «Космо-клавиатура» (диздок, раздел 5): светящиеся галактические клавиши, гравитация
 * ×0,6, раз в 45 с вместо клавиши падает «Метеорчик». Размеры форм — как в мире 1.
 */
export const WORLD3_SPACE: ThemeData = {
  id: 'space',
  name: { ru: 'Космо-клавиатура', en: 'Cosmo Keyboard' },
  shortName: { ru: 'Космо', en: 'Cosmo' },
  about: { ru: 'Лёгкие клавиши и Метеорчик', en: 'Floaty keys and Little Meteor' },
  physics: { restitution: 0.15, gravityScale: 0.6 },
  specials: { meteor: { everyMs: 45_000, size: 1.1 } },
  finish: 'cosmic',
  backdrop: { stars: '#fff7c2' },
  // Ля-минорная пентатоника, медленно и мечтательно.
  music: {
    bpm: 88,
    melody: [
      76,
      null,
      79,
      null,
      81,
      null,
      79,
      76,
      74,
      null,
      72,
      null,
      74,
      null,
      null,
      null,
      72,
      null,
      74,
      76,
      79,
      null,
      76,
      null,
      74,
      null,
      72,
      69,
      72,
      null,
      null,
      null,
    ],
    bass: [45, 45, 41, 41, 43, 43, 40, 40],
    wave: 'sine',
    decay: 0.6,
  },
  palette: {
    glass: '#e6ecff',
    glassEdge: '#a4b4ff',
    danger: '#ff7ab8',
    guide: '#e4dcff',
    face: '#1e1847',
    skyTop: '#2f3380',
    skyBottom: '#7458b8',
    pattern: '#ffffff',
    patternLine: '#b3a6f5',
  },
  forms: [
    {
      tier: 1,
      name: { ru: 'Искорка', en: 'Spark' },
      caption: { ru: 'Светится от радости', en: 'Glows with joy' },
      label: { kind: 'text', text: '+' },
      size: { w: 1, h: 1 },
      paint: { kind: 'solid', color: '#7ef9ff' },
      face: { eyes: 'big', brows: 'raised', mouth: 'o', blush: false },
      sound: { kind: 'twinkle', pitch: 1760, volume: 0.45 },
    },
    {
      tier: 2,
      name: { ru: 'Пылинка', en: 'Stardust' },
      caption: { ru: 'Летает где хочет', en: 'Floats anywhere' },
      label: { kind: 'text', text: '-' },
      size: { w: 1.2, h: 1.2 },
      paint: { kind: 'solid', color: '#cdb9ff' },
      face: { eyes: 'sly', brows: 'sly', mouth: 'smirk', blush: false },
      sound: { kind: 'twinkle', pitch: 1480, volume: 0.45 },
    },
    {
      tier: 3,
      name: { ru: 'Лунишка', en: 'Moonlet' },
      caption: { ru: 'Спит днём', en: 'Naps all day' },
      label: { kind: 'text', text: { ru: 'Ю', en: 'Q' } },
      size: { w: 1.45, h: 1.45 },
      paint: { kind: 'solid', color: '#fff0a6' },
      decor: 'craters',
      face: { eyes: 'sleepy', brows: 'none', mouth: 'smile', blush: true, extras: ['zzz'] },
      sound: { kind: 'bloop', pitch: 1175, volume: 0.55 },
    },
    {
      tier: 4,
      name: { ru: 'Кометка', en: 'Comet' },
      caption: { ru: 'С хвостиком!', en: 'Has a little tail' },
      label: { kind: 'text', text: '0' },
      size: { w: 1.7, h: 1.7 },
      paint: { kind: 'solid', color: '#ffb48c' },
      decor: 'stars',
      face: { eyes: 'wink', brows: 'none', mouth: 'grin', blush: true },
      sound: { kind: 'twinkle', pitch: 988, volume: 0.55 },
    },
    {
      tier: 5,
      name: { ru: 'Спутник', en: 'Satellite' },
      caption: { ru: 'Ловит сигналы', en: 'Catches signals' },
      label: { kind: 'text', text: '↓' },
      size: { w: 2, h: 2 },
      paint: { kind: 'solid', color: '#9ff0cf' },
      face: { eyes: 'round', brows: 'raised', mouth: 'smile', blush: false, extras: ['glasses'] },
      sound: { kind: 'pik', pitch: 784, volume: 0.6 },
    },
    {
      tier: 6,
      name: { ru: 'Планетка', en: 'Planet' },
      caption: { ru: 'Кружится весь день', en: 'Spins all day' },
      label: { kind: 'text', text: 'Fn' },
      size: { w: 2.4, h: 2 },
      paint: { kind: 'solid', color: '#8fd3ff' },
      decor: 'craters',
      face: { eyes: 'happy', brows: 'none', mouth: 'grin', blush: true },
      sound: { kind: 'bloop', pitch: 659, volume: 0.6 },
    },
    {
      tier: 7,
      name: { ru: 'Ракета', en: 'Rocket' },
      caption: { ru: 'Поехали!', en: 'Ready for liftoff!' },
      label: { kind: 'text', text: 'Ins' },
      size: { w: 2.8, h: 2.1 },
      paint: { kind: 'solid', color: '#ff9ccb' },
      decor: 'stars',
      face: { eyes: 'big', brows: 'raised', mouth: 'shout', blush: false },
      sound: { kind: 'whoosh', pitch: 523, volume: 0.75 },
    },
    {
      tier: 8,
      name: { ru: 'Сатурнчик', en: 'Ringo' },
      caption: { ru: 'Носит колечко', en: 'Wears a ring' },
      label: { kind: 'text', text: 'PgUp' },
      size: { w: 3.2, h: 2.2 },
      paint: { kind: 'solid', color: '#f6cf8c' },
      decor: 'rings',
      face: { eyes: 'shy', brows: 'worried', mouth: 'wavy', blush: true },
      sound: { kind: 'twinkle', pitch: 440, volume: 0.75, echo: 0.16 },
    },
    {
      tier: 9,
      name: { ru: 'Туманность', en: 'Nebula' },
      caption: { ru: 'Мечтает о звёздах', en: 'Dreams of stars' },
      label: { kind: 'text', text: 'End' },
      size: { w: 3.4, h: 2.6 },
      paint: { kind: 'solid', color: '#d8a6ff' },
      decor: 'swirl',
      face: { eyes: 'sleepy', brows: 'none', mouth: 'o', blush: true },
      sound: { kind: 'clack', pitch: 349, volume: 0.85, echo: 0.2 },
    },
    {
      tier: 10,
      name: { ru: 'Галактика', en: 'Galaxy' },
      caption: { ru: 'Звёзд не сосчитать', en: 'Too many stars' },
      label: { kind: 'text', text: 'F12' },
      size: { w: 3.8, h: 2.6 },
      paint: { kind: 'solid', color: '#8cb8ff' },
      decor: 'swirl',
      face: { eyes: 'star', brows: 'cheeky', mouth: 'grin', blush: false },
      sound: { kind: 'whoosh', pitch: 262, volume: 0.8 },
    },
    {
      tier: 11,
      name: { ru: 'КОСМО-ПРОБЕЛ', en: 'COSMO SPACEBAR' },
      caption: { ru: 'Король космоса', en: 'King of the cosmos' },
      label: { kind: 'glyph', glyph: 'crown' },
      size: { w: 6, h: 2.4 },
      paint: {
        kind: 'rainbow',
        colors: ['#7ef9ff', '#8fb8ff', '#c9a6ff', '#ff9ad5', '#ffd29a', '#fff3a8'],
      },
      decor: 'stars',
      face: { eyes: 'star', brows: 'none', mouth: 'grin', blush: true, extras: ['sparkles'] },
      sound: { kind: 'fanfare', pitch: 196, volume: 0.9 },
    },
  ],
};
