import type { ThemeData } from './types';

/** Мир 1 «Клац-Классика»: обычная физика, 11 форм (диздок, разделы 4 и 5). */
export const WORLD1_CLASSIC: ThemeData = {
  id: 'classic',
  name: { ru: 'Клац-Классика', en: 'Clack Classic' },
  shortName: { ru: 'Классика', en: 'Classic' },
  about: { ru: 'Обычные мягкие клавиши', en: 'Classic squishy keys' },
  physics: { restitution: 0.15, gravityScale: 1 },
  specials: {},
  finish: 'plastic',
  backdrop: {},
  // Две фразы по 16 восьмых в до-мажорной пентатонике: лёгкий мотив, который не надоедает.
  music: {
    bpm: 104,
    melody: [
      72,
      null,
      76,
      79,
      81,
      null,
      79,
      76,
      74,
      null,
      76,
      79,
      76,
      null,
      72,
      null,
      74,
      null,
      76,
      79,
      84,
      null,
      81,
      79,
      76,
      null,
      74,
      76,
      72,
      null,
      null,
      null,
    ],
    bass: [48, 48, 45, 45, 41, 41, 43, 43],
    wave: 'triangle',
    decay: 0.3,
  },
  palette: {
    glass: '#ffffff',
    glassEdge: '#8ec5f0',
    danger: '#ff6f91',
    guide: '#6b5fb3',
    face: '#3a2e6e',
    skyTop: '#bfe6ff',
    skyBottom: '#ffd9ee',
    pattern: '#ffffff',
    patternLine: '#b8b0e8',
  },
  forms: [
    {
      tier: 1,
      name: { ru: 'Точка', en: 'Dot' },
      caption: { ru: 'Маленькая, но важная', en: 'Tiny but mighty' },
      label: { kind: 'text', text: '.' },
      size: { w: 1, h: 1 },
      paint: { kind: 'solid', color: '#9ff0cf' },
      face: { eyes: 'big', brows: 'raised', mouth: 'o', blush: false },
      sound: { kind: 'pik', pitch: 1760, volume: 0.5 },
    },
    {
      tier: 2,
      name: { ru: 'Запятулька', en: 'Comma' },
      caption: { ru: 'Любит паузы, хитрюга', en: 'Loves a little pause' },
      label: { kind: 'text', text: ',' },
      size: { w: 1.2, h: 1.2 },
      paint: { kind: 'solid', color: '#fff08a' },
      face: { eyes: 'sly', brows: 'sly', mouth: 'smirk', blush: false },
      sound: { kind: 'pik', pitch: 1320, volume: 0.5 },
    },
    {
      tier: 3,
      name: { ru: 'Буквуля', en: 'Letter' },
      caption: { ru: 'Знает весь алфавит', en: 'Knows the alphabet' },
      label: { kind: 'text', text: { ru: 'Ы', en: 'A' } },
      size: { w: 1.45, h: 1.45 },
      paint: { kind: 'solid', color: '#ffc49b' },
      face: { eyes: 'happy', brows: 'none', mouth: 'grin', blush: true },
      sound: { kind: 'tuk', pitch: 880, volume: 0.6 },
    },
    {
      tier: 4,
      name: { ru: 'Циферка', en: 'Number' },
      caption: { ru: 'Считает до семи', en: 'Counts to seven' },
      label: { kind: 'text', text: '7' },
      size: { w: 1.7, h: 1.7 },
      paint: { kind: 'solid', color: '#8fd3ff' },
      face: { eyes: 'wink', brows: 'none', mouth: 'smile', blush: true },
      sound: { kind: 'tuk', pitch: 660, volume: 0.6 },
    },
    {
      tier: 5,
      name: { ru: 'Стрелочка', en: 'Arrow' },
      caption: { ru: 'Всегда смотрит вверх', en: 'Always looks up' },
      label: { kind: 'text', text: '↑' },
      size: { w: 2, h: 2 },
      paint: { kind: 'solid', color: '#c8f27a' },
      face: { eyes: 'round', brows: 'raised', mouth: 'grin', blush: false },
      sound: { kind: 'chpok', pitch: 520, volume: 0.65 },
    },
    {
      tier: 6,
      name: { ru: 'Таб', en: 'Tab' },
      caption: { ru: 'Спит на ходу', en: 'Naps on the go' },
      label: { kind: 'text', text: 'Tab' },
      size: { w: 2.4, h: 2 },
      paint: { kind: 'solid', color: '#d7b8ff' },
      face: { eyes: 'sleepy', brows: 'none', mouth: 'o', blush: false, extras: ['zzz'] },
      sound: { kind: 'clack', pitch: 440, volume: 0.55 },
    },
    {
      tier: 7,
      name: { ru: 'Капс', en: 'Caps' },
      caption: { ru: 'ГОВОРИТ ГРОМКО', en: 'TALKS VERY LOUD' },
      label: { kind: 'text', text: 'CAPS' },
      size: { w: 2.8, h: 2.1 },
      paint: { kind: 'solid', color: '#ffa8d2' },
      face: { eyes: 'big', brows: 'none', mouth: 'shout', blush: false },
      sound: { kind: 'clack', pitch: 392, volume: 0.9 },
    },
    {
      tier: 8,
      name: { ru: 'Шифт', en: 'Shift' },
      caption: { ru: 'Скромный помощник', en: 'Shy little helper' },
      label: { kind: 'text', text: 'Shift' },
      size: { w: 3.2, h: 2.2 },
      paint: { kind: 'solid', color: '#ff8f84' },
      face: { eyes: 'shy', brows: 'worried', mouth: 'wavy', blush: true },
      sound: { kind: 'clack', pitch: 349, volume: 0.75, echo: 0.14 },
    },
    {
      tier: 9,
      name: { ru: 'Энтер', en: 'Enter' },
      caption: { ru: 'Умник в очках', en: 'Smart in glasses' },
      label: { kind: 'text', text: 'Enter' },
      size: { w: 3.4, h: 2.6 },
      paint: { kind: 'solid', color: '#3fd49b' },
      face: { eyes: 'round', brows: 'proud', mouth: 'smile', blush: false, extras: ['glasses'] },
      sound: { kind: 'clack', pitch: 262, volume: 0.9 },
    },
    {
      tier: 10,
      name: { ru: 'Бэкспейс', en: 'Backspace' },
      caption: { ru: 'Стирает и хихикает', en: 'Erases and giggles' },
      label: { kind: 'glyph', glyph: 'backspace' },
      size: { w: 3.8, h: 2.6 },
      paint: { kind: 'solid', color: '#9d85ff' },
      face: { eyes: 'round', brows: 'cheeky', mouth: 'grin', blush: false, extras: ['tongue'] },
      sound: { kind: 'whoosh', pitch: 220, volume: 0.8 },
    },
    {
      tier: 11,
      name: { ru: 'ПРОБЕЛ', en: 'SPACEBAR' },
      caption: { ru: 'Король клавиатуры', en: 'King of the keyboard' },
      label: { kind: 'glyph', glyph: 'crown' },
      size: { w: 6, h: 2.4 },
      paint: {
        kind: 'rainbow',
        colors: ['#ff9aa2', '#ffc98f', '#fff08a', '#9ff0cf', '#8fd3ff', '#c3a8ff'],
      },
      face: { eyes: 'star', brows: 'none', mouth: 'grin', blush: true, extras: ['sparkles'] },
      sound: { kind: 'fanfare', pitch: 196, volume: 0.9 },
    },
  ],
};
