import type { ThemeData } from './types';

/**
 * Мир 2 «Сладкая клавиатура» (диздок, раздел 5): мармеладные и шоколадные клавиши, упругость
 * выше (0,35 против 0,15), изредка падает липкая «Карамелька». Размеры форм — как в мире 1.
 */
export const WORLD2_CANDY: ThemeData = {
  id: 'candy',
  name: { ru: 'Сладкая клавиатура', en: 'Sweet Keyboard' },
  shortName: { ru: 'Сладкая', en: 'Sweet' },
  about: { ru: 'Прыгучие клавиши и липкая Карамелька', en: 'Bouncy keys and sticky Caramel' },
  physics: { restitution: 0.35, gravityScale: 1 },
  specials: { caramel: { chance: 0.06, holdMs: 3000 } },
  finish: 'jelly',
  backdrop: { sprinkles: ['#ff8fb8', '#8fd3ff', '#ffe066', '#7fe0b8', '#c9a6ff'] },
  // Соль-мажорная пентатоника, отрывисто и вприпрыжку.
  music: {
    bpm: 120,
    melody: [
      74,
      71,
      74,
      76,
      79,
      null,
      76,
      74,
      71,
      null,
      69,
      71,
      67,
      null,
      null,
      null,
      69,
      71,
      74,
      null,
      76,
      74,
      71,
      69,
      71,
      null,
      74,
      71,
      67,
      null,
      null,
      null,
    ],
    bass: [43, 43, 40, 40, 36, 36, 38, 38],
    wave: 'triangle',
    decay: 0.18,
  },
  palette: {
    glass: '#fff8fc',
    glassEdge: '#f4a6c8',
    danger: '#ff5f8f',
    guide: '#b45a86',
    face: '#5b2b3f',
    skyTop: '#ffe1ef',
    skyBottom: '#fff1d6',
    pattern: '#ffffff',
    patternLine: '#f3b6cf',
  },
  forms: [
    {
      tier: 1,
      name: { ru: 'Драже', en: 'Sprinkle' },
      caption: { ru: 'Хрустит от смеха', en: 'Crunchy giggles' },
      label: { kind: 'text', text: '*' },
      size: { w: 1, h: 1 },
      paint: { kind: 'solid', color: '#ff9ec7' },
      face: { eyes: 'happy', brows: 'none', mouth: 'smile', blush: true },
      sound: { kind: 'bloop', pitch: 1568, volume: 0.5 },
    },
    {
      tier: 2,
      name: { ru: 'Ирисочка', en: 'Toffee' },
      caption: { ru: 'Тянется к друзьям', en: 'Sticks to friends' },
      label: { kind: 'text', text: ';' },
      size: { w: 1.2, h: 1.2 },
      paint: { kind: 'solid', color: '#efb27a' },
      finish: 'plastic',
      face: { eyes: 'sly', brows: 'sly', mouth: 'smirk', blush: false },
      sound: { kind: 'tuk', pitch: 1320, volume: 0.5 },
    },
    {
      tier: 3,
      name: { ru: 'Мармеладка', en: 'Gummy' },
      caption: { ru: 'Прыгает без устали', en: 'Bounces all day' },
      label: { kind: 'text', text: { ru: 'Ж', en: 'G' } },
      size: { w: 1.45, h: 1.45 },
      paint: { kind: 'solid', color: '#ff8a8a' },
      face: { eyes: 'wink', brows: 'none', mouth: 'grin', blush: true },
      sound: { kind: 'boing', pitch: 1046, volume: 0.55 },
    },
    {
      tier: 4,
      name: { ru: 'Зефирка', en: 'Marshmallow' },
      caption: { ru: 'Мягче облачка', en: 'Softer than a cloud' },
      label: { kind: 'text', text: '8' },
      size: { w: 1.7, h: 1.7 },
      paint: { kind: 'solid', color: '#ffd3e6' },
      finish: 'plastic',
      face: { eyes: 'happy', brows: 'none', mouth: 'wavy', blush: true },
      sound: { kind: 'bloop', pitch: 880, volume: 0.6 },
    },
    {
      tier: 5,
      name: { ru: 'Леденец', en: 'Lollipop' },
      caption: { ru: 'Сладко сияет', en: 'Sweet and shiny' },
      label: { kind: 'glyph', glyph: 'heart' },
      size: { w: 2, h: 2 },
      paint: { kind: 'solid', color: '#8fe0ff' },
      decor: 'stripes',
      face: { eyes: 'round', brows: 'raised', mouth: 'grin', blush: false },
      sound: { kind: 'chpok', pitch: 698, volume: 0.65 },
    },
    {
      tier: 6,
      name: { ru: 'Пончик', en: 'Donut' },
      caption: { ru: 'Улыбка с дырочкой', en: 'A smile with a hole' },
      label: { kind: 'text', text: 'Esc' },
      size: { w: 2.4, h: 2 },
      paint: { kind: 'solid', color: '#ffb0d6' },
      finish: 'plastic',
      decor: 'sprinkles',
      face: { eyes: 'big', brows: 'raised', mouth: 'o', blush: false },
      sound: { kind: 'boing', pitch: 587, volume: 0.6 },
    },
    {
      tier: 7,
      name: { ru: 'Печенька', en: 'Cookie' },
      caption: { ru: 'Обожает молоко', en: 'Loves milk' },
      label: { kind: 'text', text: 'Ctrl' },
      size: { w: 2.8, h: 2.1 },
      paint: { kind: 'solid', color: '#e2ac72' },
      finish: 'plastic',
      decor: 'chips',
      face: { eyes: 'happy', brows: 'none', mouth: 'grin', blush: true },
      sound: { kind: 'clack', pitch: 494, volume: 0.8 },
    },
    {
      tier: 8,
      name: { ru: 'Мороженка', en: 'Ice Cream' },
      caption: { ru: 'Немножко мёрзнет', en: 'A little chilly' },
      label: { kind: 'text', text: 'Alt' },
      size: { w: 3.2, h: 2.2 },
      paint: { kind: 'solid', color: '#b5f0d6' },
      decor: 'drips',
      face: { eyes: 'shy', brows: 'worried', mouth: 'wavy', blush: true },
      sound: { kind: 'clack', pitch: 415, volume: 0.75, echo: 0.12 },
    },
    {
      tier: 9,
      name: { ru: 'Шоколадка', en: 'Choco Bar' },
      caption: { ru: 'Тает от похвалы', en: 'Melts at compliments' },
      label: { kind: 'text', text: 'Home' },
      size: { w: 3.4, h: 2.6 },
      paint: { kind: 'solid', color: '#c58e62' },
      finish: 'plastic',
      decor: 'drizzle',
      face: { eyes: 'happy', brows: 'proud', mouth: 'smile', blush: true },
      sound: { kind: 'clack', pitch: 349, volume: 0.9 },
    },
    {
      tier: 10,
      name: { ru: 'Капкейк', en: 'Cupcake' },
      caption: { ru: 'Носит вишенку', en: 'Wears a cherry' },
      label: { kind: 'text', text: 'Del' },
      size: { w: 3.8, h: 2.6 },
      paint: { kind: 'solid', color: '#d9bcff' },
      decor: 'cherry',
      face: { eyes: 'round', brows: 'cheeky', mouth: 'grin', blush: false, extras: ['tongue'] },
      sound: { kind: 'boing', pitch: 247, volume: 0.8 },
    },
    {
      tier: 11,
      name: { ru: 'ТОРТ-ПРОБЕЛ', en: 'CAKE SPACEBAR' },
      caption: { ru: 'Праздник каждый день', en: 'A party every day' },
      label: { kind: 'glyph', glyph: 'crown' },
      size: { w: 6, h: 2.4 },
      paint: {
        kind: 'rainbow',
        colors: ['#ffb3c8', '#ffd59e', '#fff2a8', '#c8f5c0', '#bfe3ff', '#e2c6ff'],
      },
      decor: 'drips',
      face: { eyes: 'star', brows: 'none', mouth: 'grin', blush: true, extras: ['sparkles'] },
      sound: { kind: 'fanfare', pitch: 196, volume: 0.9 },
    },
  ],
};
